name: CI

on:
  push:
    branches: ["*"]
  pull_request:
    branches: ["*"]
  workflow_dispatch:

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build crndm_derive
      run: cargo build -p crndm_derive --all-targets
    - name: Build Corundum
      run: cargo build -p corundum --all-targets

  test:
    runs-on: ubuntu-latest
    needs:
    - build
    steps:
    - uses: actions/checkout@v3
    - name: Run tests
      run: cargo test --tests --verbose -- --test-threads=1

  lint:
    runs-on: ubuntu-latest
    continue-on-error: true
    needs:
    - build
    steps:
    - uses: actions/checkout@v3
    - name: Run clippy
      run: cargo clippy
